export const theme = {
  colors: {
    primary: "#170C3A",
    secondary: "",
    white: "#FFFFFF",
    darkWhite: "#FCFCFD",
    darkerWhite: "#F5F4F6",
    darkestWhite: "#EBEAED",
    mostDarkestWhite: "#DEDCE1",
    ink: "#170C3A",
    lightInk: "#8F8A9B",
    ligherInk: "#B1ADB9",
    lighestInk: "#C7C4CD",
    blue: "#365DF0",
    darkBlue: "#2F55CC",
    darkerBlue: "#244AA8",
    lightBlue: "#9AAEF7",
    lighterBlue: "#B9C6FA",
    lightestBlue: "#CAD6FC",
    mostLightestBlue: "#E1E7FD",
    error: "#F95E5A",
    lightError: "#FEEFEE",
  },
};
